import { defineConfig, globalIgnores } from "eslint/config";
import path from "node:path";
import { fileURLToPath } from "node:url";
import js from "@eslint/js";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const compat = new FlatCompat({
    baseDirectory: __dirname,
    recommendedConfig: js.configs.recommended,
    allConfig: js.configs.all
});

export default defineConfig([
  globalIgnores([
    "**/node_modules/",
    "**/dist/",
    "**/build/",
    "**/types/",
    "**/*.d.ts",
    // Generated by TanStack Router
    "apps/web/src/routeTree.gen.ts",
    "src/routeTree.gen.ts",
    "**/routeTree.gen.ts",
  ]),
  {
    extends: compat.extends("expo"),
    rules: {},
  },
  // UI package uses barrel re-exports that conflict with import/export rule
  {
    files: ["packages/ui/**"],
    rules: {
      "import/export": "off",
    },
  },
]);