// AUTO-GENERATED by scripts/generateResources.ts
import common_en from '../locales/common/en.json';
import common_fr from '../locales/common/fr.json';
const resources: any = {};
resources['en'] = {
  'common': common_en,
};
resources['fr'] = {
  'common': common_fr,
};
export default resources;